spring:
  datasource:
    url: jdbc:mysql://localhost:3305/test_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "root"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true